name: store-sales-stgat
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.12

  # Core data science packages (conda-managed for better compatibility)
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Statistical packages
  - statsmodels>=0.14.0

  # Visualization
  - plotly>=5.15.0

  # Web frameworks
  - flask>=2.3.0

  # Jupyter ecosystem
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.25.0
  - ipywidgets>=8.0.0

  # Development tools
  - pytest>=7.4.0
  - black>=23.7.0

  # Neural model dependencies (PyTorch ecosystem)
  # Note: Install these from conda for better CUDA/system integration
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - cpuonly  # Remove this line if you have NVIDIA GPU and want CUDA support

  # PyTorch Geometric (from pyg channel)
  - pyg>=2.6.0

  # Utilities
  - networkx>=3.1
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - requests>=2.31.0

  # Additional dependencies from pip
  - pip
  - pip:
    # Packages not available in conda or need specific versions
    - pmdarima>=2.0.0,<3.0.0
    - streamlit>=1.25.0,<2.0.0
    - pytorch-lightning==2.5.2
    - lightning-utilities==0.14.3
    - torchmetrics==1.7.4
    - pydantic>=2.0.0,<3.0.0
    - openpyxl>=3.1.0,<4.0.0
    - python-dateutil>=2.8.0,<3.0.0
    - coverage>=7.2.0,<8.0.0

# Environment variables (optional)
variables:
  - PYTHONPATH: ${CONDA_PREFIX}/src

# Usage:
# 1. Create environment: conda env create -f environment.yml
# 2. Activate environment: conda activate store-sales-stgat
# 3. Install project in editable mode: pip install -e .